# Site settings
title: TechBlog by Dhiraj
email: contact@dhirajsalian.com
description: >- 
  TechBlog by Dhiraj aims to bring anything and everything related to 
  Computer Science to you. We will be adding blogs on range of topics
  such as Programming, Data Structures & Algorithms, System Design, Design 
  Patterns, Java, JavaScript, TypeScript, Dart, Spring, Flutter and Angular.
baseurl: "/"
url: "https://blogs.dhirajsalian.com"
github_username:  dhiraj-salian

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude settings
exclude:
  - techblog.code-workspace
