# Site settings
title: TechBlog by Dhiraj
year: 2021
email: contact@dhirajsalian.com
author: Dhiraj Salian
description: >- 
  Sharing my understanding on designing,
  developing and deploying quality code.
baseurl: "/"
url: "https://blogs.dhirajsalian.com"
portfolio_hostname: "dhirajsalian.com"
github_username:  dhiraj-salian
linkedin_username: dhiraj-salian
rss: Subscribe

# Build settings
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true
show_about_footer: true
markdown: GFM

# Exclude settings
exclude:
  - techblog.code-workspace

# Disqus settings
# disqus:
#   shortname: techblog_by_dhiraj