# Site settings
title: TechBlog by Dhiraj
email: contact@dhirajsalian.com
description: >- 
  Sharing my experiences on designing,
  developing and deploying quality code.
baseurl: "/"
url: "https://blogs.dhirajsalian.com"
github_username:  dhiraj-salian

# Build settings
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true
markdown: GFM

# Exclude settings
exclude:
  - techblog.code-workspace
