# Site settings
title: TechBlog by Dhiraj
year: 2021
email: contact@dhirajsalian.com
author: Dhiraj Salian
description: >- 
  Experiences on Design, Develop & Deploy.
baseurl: "/"
url: "https://blogs.dhirajsalian.com"
rss: Subscribe

# Build settings
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true
show_about_footer: true
markdown: GFM

# Exclude settings
exclude:
  - techblog.code-workspace
  - .idea/

# Disqus settings
disqus:
  shortname: blogs-dhirajsalian-com